name: AWS SecretsManager to bazelrc file
description: Take a SecretsManager path and convert the content into a .bazelrc file
author: https://github.com/buildkite-plugins
public: true
requirements:
  - aws
  - bash
  - jq
configuration:
  properties:
    bazel-config:
      type: string
      default: "buildkite"
    output-filename:
      type: string
      default: ".bazelrc-buildkite"
    path:
      type: string
  required:
    - path
  additionalProperties: false
